### ISSUE TITLE
Definition der Datenaustauschobjekte zur Kommunikation via API

### ISSUE THREAD

**Issue by BravoEchoNov** [HSFDWS23-24/ShortcutTrainer-backEnd#2]
Aufbau im JSON Format
Inhaltlich weitergehend als die Datenbankentitäten -> es sollten alle Informationen enthalten sein, die im Backend notwendig sind, um die Anwendungslogik umzusetezn, aber auch alles was im Forntend notwendig ist, um eben diese Anwendungslogik anzuzeigen und die Interaktion des Benutzers mit der Anwendung zu ermöglichen

**Comment by paulSchaefer03** [comment]
Wir haben in der Datei "JSON_Objekte" ein Format mit den Notwendigen JSON Objekten definiert die vom FE bzw. BE benötigt werden. Zu dem ist beschrieben für was und wie die Obkjekte verwendet werden können.

Wäre gut wenn sich die Datei jemand mal anschaut ob das dobere Issue beantwortet.

**Comment by BravoEchoNov** [comment]
Jeder aus dem Team "Backend" kann es sich erstmal anschauen und Gedanken dazu machen, ob das passt oder was noch geändert werden müsste. Am Donnerstag müssen wir uns dann mit möglichen Branching und Review-Strategien beschäftigen
