### ISSUE TITLE
BE: Deployment PostgreSQL DB

### ISSUE THREAD

**Issue by BravoEchoNov** [HSFDWS23-24/ShortcutTrainer-backEnd#22]
Eine PostgreSQL DB in Azure erstellen und ggf das Skript zur Erstellung der Tabellen aufspielen (ShortcutTrainerBackend/ShortcutTrainerBackend/Database/create_tables.sql)

**Comment by SeminSey** [comment]
Postgres DB is now reachable under `db-shortcut-be-dev-gercentral-100.postgres.database.azure.com`
