### ISSUE TITLE
Einrichtung der Entwicklungsumgebung

### ISSUE THREAD

**Issue by BravoEchoNov** [HSFDWS23-24/ShortcutTrainer-backEnd#5]
- [ ] Installieren von dotnet7.0 [](https://dotnet.microsoft.com/en-us/download) -> überprüfen mit Terminal/PowerShell durch Eingabe von "dotnet --version" (Output sollte 7.0.xxx sein)
- [ ] Entwicklungsumgebung
      - Microsoft Visual Studio 2022 Community [](https://visualstudio.microsoft.com/de/downloads/)
      - JetBrains Rider [](https://www.jetbrains.com/de-de/rider/)
- [ ] GitHub-Repository klonen -> im Repo die .sln-Datei mit gewählter IDE öffnen -> Build Project (wenn Build erfolgreich war, konnten alle Pakete automatich installiert werden, ansonsten "NuGet Restore" für jeweilige IDE ausführen) -> Anwendung starten (öffnet im Standard-Browser ein Fenster mit Swagger, über welche man alle verfügbaren API-Routen sieht und Requests konfigurieren und senden kann)

**Comment by Kev-Boy** [comment]
wurde nun ins Wiki verschoben
